#!/bin/bash
inicio=100
fin=15000
incremento=200
i=$inicio

echo > tiempos.dat

while [ $i -le $fin ]; do
  echo Ejecucion tam=$i
  echo `./burbujaPeor $i 10000` >> tiempos.dat
  let "i += $incremento"
done
