#!/bin/bash
inicio=100
fin=20000
incremento=100
i=$inicio

echo > tiempos.dat

while [ $i -le $fin ]; do
  echo Ejecucion tam=$i
  echo `./insercionPeor $i 10000` >> tiempos.dat
  let "i += $incremento"
done
