SRC = src
INC = include
OBJ = obj
BIN = bin
CXX = g++
CPPFLAGS = -Wall -g  -I$(INC) -c -std=c++11


all: $(BIN)/ejercicio1 $(BIN)/ejercicio2

# ************ Generación de documentación ******************
documentacion:
	doxygen doc/doxys/Doxyfile

# ************ Compilación de módulos ************
$(BIN)/ejercicio1: $(SRC)/ejercicio1.cpp
	$(CXX) -o $@ $^
$(BIN)/ejercicio2: $(SRC)/ejercicio2.cpp
	$(CXX) -o $@ $^

# ************ Limpieza ************
clean :
	-rm $(OBJ)/* $(SRC)/*~ $(INC)/*~ ./*~

mrproper : clean
	-rm $(BIN)/* doc/html/*
