#!/bin/bash
inicio=100
fin=10000
incremento=100
i=$inicio

echo > tiempos2.dat

while [ $i -le $fin ]; do
  echo Ejecucion tam=$i
  echo `./mergesort $i` >> tiempos2.dat
  let "i += $incremento"
done
